### ISSUE TITLE
Pull the content-type header from the media download response so that the s3 bucket has the right file extension

### ISSUE THREAD

**Issue by SlidewhistleIncognito** [shareOfTheMind/TelegramBot#9]

**Comment by SlidewhistleIncognito** [comment]
Something like the following should work. It pulls the content-type header and grabs the string after the forward slash (which is the extension):


`file_type = content_response.headers["Content-Type"].split("/")[1]`

**Comment by SlidewhistleIncognito** [comment]
added the change for the tiktok posts

**Comment by gabealoi** [comment]
I'll implement this for instagram posts, I will need to grab those comments too. IG implementation giving the most issues at the moment.

**Comment by gabealoi** [comment]
> Something like the following should work. It pulls the content-type header and grabs the string after the forward slash (which is the extension):
> 
> `file_type = content_response.headers["Content-Type"].split("/")[1]`

_**The file_type doesn't seem to be coming back within the response headers for requests to instagram API endpoints.**_


@SlidewhistleIncognito 
What does come back is a `media_type` key that resembles a photo, video, or reel with a number 1, 2, 3 (may not be exact mappings). 

So, in this way, there is a and variable indicative of the media type within the metadata for an instagram post. All tiktoks are videos, ?, and if not there may be something in the metadata that would tell you otherwise.
